# branches:
#   only:
#     - gh-pages
# language: ruby
# rvm:
#   - 2.0.0 # otherwise public_suffix will fail to install
# script:
#   - bundle exec jekyll build --config _config.yml,_config_dev.yml
#   - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html
# env:
#   global:
#     - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html --disable-external
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
